name: Preflight CI

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore packages
      run: dotnet restore Fishbowl.Preflight.sln

    - name: Build solution
      run: dotnet build Fishbowl.Preflight.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test Fishbowl.Preflight.sln --configuration Release --no-build --verbosity normal

  pack-and-publish:
    runs-on: windows-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore
      run: dotnet restore Fishbowl.Preflight.sln

    - name: Build Fishbowl.Preflight
      run: dotnet build src/Fishbowl.Preflight/Fishbowl.Preflight.csproj -c Release --no-restore

    - name: Build Fishbowl.Preflight.AspNetCore
      run: dotnet build src/Fishbowl.Preflight.AspNetCore/Fishbowl.Preflight.AspNetCore.csproj -c Release --no-restore

    - name: Check that DLLs exist
      run: |
        dir src\Fishbowl.Preflight\bin\Release\net8.0
        dir src\Fishbowl.Preflight.AspNetCore\bin\Release\net8.0

    - name: Pack Fishbowl.Preflight
      run: dotnet pack src/Fishbowl.Preflight/Fishbowl.Preflight.csproj -c Release --no-build

    - name: Pack Fishbowl.Preflight.AspNetCore
      run: dotnet pack src/Fishbowl.Preflight.AspNetCore/Fishbowl.Preflight.AspNetCore.csproj -c Release --no-build

    - name: Publish to NuGet
      run: dotnet nuget push src/**/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
