name: Preflight CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Enable publish step on tag push
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore packages
      run: dotnet restore Fishbowl.Preflight.sln

    - name: Build solution
      run: dotnet build Fishbowl.Preflight.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test Fishbowl.Preflight.sln --configuration Release --no-build --verbosity normal

  pack-and-publish:
    runs-on: windows-latest
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Pack Preflight
      run: dotnet pack src/Fishbowl.Preflight/Fishbowl.Preflight.csproj -c Release -o ./artifacts

    - name: Pack Preflight.AspNetCore
      run: dotnet pack src/Fishbowl.Preflight.AspNetCore/Fishbowl.Preflight.AspNetCore.csproj -c Release -o ./artifacts

    - name: Push to NuGet
      run: dotnet nuget push artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
